### PR TITLE
Update Snapmaker profiles

### PR DESCRIPTION
**Pull request by macdylan**

### CODE REVIEW

**Comment by macdylan** [comment]
Please let me know if the project is still expected

**Comment by fr3ak2402** [comment]
Yes this project is still current and is still being worked on, for now I am working on another slicer.... this project will also go into this other slicer. Additionally I am in the process of changing all the filaments so they all have `@base` etc....

**Comment by fr3ak2402** [comment]
One thing I noticed right away, in your PR you removed the Snapmaker Artisan?

**Comment by macdylan** [comment]
I don't have Artisan so I can't verify it.
Besides, the gcode of your profile does not have necessary actions such as preheating and wiping.

I don't think it will work correctly.

**Comment by fr3ak2402** [comment]
Yes True, I built the profile based on the Snapmaker profile....

Actually the GCode of the A350 should fit for the Artisan, that this is actually only an A400...
In addition, both also use the same attachments, such as dual exturder, etc.

**Comment by macdylan** [comment]
I think the dual extruder needs another configs for A250/350, there are a lot of differences with the single extruder such as 
 printable area, standby temperature, retract length, toolchange gcode, etc., they have completely different hardware things like fan, extrusion gear & motor.

**Comment by fr3ak2402** [comment]
Okay, I saw that the A250/A350 are single extruder machines.... but a dual extruder machine from the A350 should actually work with an Artisan...

I am just thinking how to solve this with the different models. Because there are printers that can print single, dual, idex, mixer, left, right. 
So I think that I still have to adjust the prefix of the file names again and adjust in the wiki of the repository, so that the documentation is up to date.

I think I will solve this so that the following naming is done for single extenders:

Printer machine nozzle (Single Extruder) -> {Printer manufacturer} {machine name} ({nozzle diameter} nozzle).json

Printer machine nozzle (Mixer, Dual, IDEX, Left, Right) -> {Printer manufacturer} {machine name} ({nozzle diameter} nozzle) (machine variant).json

Examples:
Snapmaker A250 (0.4 nozzle).json

Snapmaker J1 (0.4 nozzle) (IDEX).json

Snapmaker A250 (0.4 nozzle) (Dual).json
Snapmaker A250 (0.4 nozzle) (Left).json
Snapmaker A250 (0.4 nozzle) (Right).json

Sovol SV02 (0.4 nozzle) (Mixer).json

To be able to print only with the left or right nozzle is only possible with an IDEX or dual extruder.

In this way, the machine variant can also be better added in the future if there are different variants of a printer model. Like for example attachments or different extruder types like a mixer extruder.

**Comment by fr3ak2402** [comment]
@macdylan 
Can you rename the J1 like this?

Snapmaker J1 (0.4 nozzle) (IDEX).json

**Pull request closed without merging**
